name: Workflow Demo

on: 
  push

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}
  SEC: ${{secrets.abc}}
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Echo ACCESS_ID
      run: |
        echo ${ACCESS_ID}
        echo ${{ vars.TEST }}
        echo ${{ secrets.abc}}
        echo ${{ env.SEC}}
        export STEP=done
        echo $STEP
    - name: Echo Sec
      if: ${{vars.ACCESS_ID}} == kode-kloud-123456
      run: |
       echo ${{ secrets.abc}}
       echo ${{ env.SEC}}
       echo $STEP
          
